In [1]:
import torch
import numpy as np

### Create Basic Tensors

In [2]:
# 1D Tensor
t1 = torch.tensor([1, 2, 3, 4])
print("1D Tensor:", t1)

# 2D Tensor
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n2D Tensor:\n", t2)

# Random Tensor
t3 = torch.rand((3, 4))
print("\nRandom 3x4 Tensor:\n", t3)


1D Tensor: tensor([1, 2, 3, 4])

2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Random 3x4 Tensor:
 tensor([[0.4924, 0.6702, 0.3857, 0.4652],
        [0.6244, 0.5120, 0.7671, 0.2305],
        [0.0332, 0.2511, 0.4984, 0.4011]])


Tensors are generalizations of matrices:

1D tensor → vector

2D tensor → matrix

n-D tensor → multidimensional data (used in deep learning)

### Tensor Reshaping

In [3]:
print("Original shape:", t3.shape)

# Reshape 3x4 → 2x6
reshaped = t3.reshape(2, 6)
print("Reshaped (2x6):\n", reshaped)

# Flatten tensor
flattened = t3.flatten()
print("\nFlattened:\n", flattened)


Original shape: torch.Size([3, 4])
Reshaped (2x6):
 tensor([[0.4924, 0.6702, 0.3857, 0.4652, 0.6244, 0.5120],
        [0.7671, 0.2305, 0.0332, 0.2511, 0.4984, 0.4011]])

Flattened:
 tensor([0.4924, 0.6702, 0.3857, 0.4652, 0.6244, 0.5120, 0.7671, 0.2305, 0.0332,
        0.2511, 0.4984, 0.4011])


.reshape() changes shape without changing data.

.flatten() converts to 1D (important for neural networks).

### Broadcasting Example

In [5]:
A = torch.rand((3, 1))   # shape: (3,1)
B = torch.rand((1, 4))   # shape: (1,4)

print("A:\n", A)
print("\nB:\n", B)

# Broadcasting: A (3,1) expands to (3,4), B (1,4) expands to (3,4)
C = A + B
print("\nBroadcasted Addition (3x4):\n", C)


A:
 tensor([[0.2718],
        [0.2433],
        [0.8393]])

B:
 tensor([[0.3081, 0.9993, 0.2176, 0.9213]])

Broadcasted Addition (3x4):
 tensor([[0.5799, 1.2711, 0.4894, 1.1931],
        [0.5514, 1.2426, 0.4609, 1.1646],
        [1.1474, 1.8386, 1.0570, 1.7606]])


PyTorch aligns dimensions from right to left:

Tensor A	Tensor B	Compatible?
(3, 1)	(1, 4)	✔ yes
(3, 5)	(5,)	✔ yes
(3, 4)	(2, 4)	❌ no

### Element-wise Operations

In [6]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([0.5, 1.5, 2.5])

print("Addition:", x + y)
print("Multiplication:", x * y)
print("Power:", x ** 2)
print("Log:", torch.log(x))


Addition: tensor([1.5000, 3.5000, 5.5000])
Multiplication: tensor([0.5000, 3.0000, 7.5000])
Power: tensor([1., 4., 9.])
Log: tensor([0.0000, 0.6931, 1.0986])


Element-wise ops match NumPy but run on GPU if available.

### Matrix Multiplication

In [7]:
M = torch.randn(3, 2)
N = torch.randn(2, 4)

print("Matrix M:\n", M)
print("\nMatrix N:\n", N)

# Matrix multiply
P = torch.matmul(M, N)
print("\nMatrix Product (3x4):\n", P)


Matrix M:
 tensor([[-0.3718,  1.4817],
        [-1.1152,  0.3471],
        [ 0.3979, -0.9234]])

Matrix N:
 tensor([[ 0.9762, -0.6594, -0.5348, -1.4236],
        [ 1.4992, -1.8282, -0.5832, -0.8468]])

Matrix Product (3x4):
 tensor([[ 1.8584, -2.4636, -0.6653, -0.7254],
        [-0.5683,  0.1008,  0.3940,  1.2937],
        [-0.9960,  1.4258,  0.3257,  0.2155]])


Pytorch uses:

torch.matmul(A, B)

or shortcut A @ B

### Reduction Operations (sum, mean, max)

In [8]:
R = torch.rand((3, 4))

print("Tensor R:\n", R)
print("\nSum over rows (dim=1):", R.sum(dim=1))
print("Sum over columns (dim=0):", R.sum(dim=0))
print("Mean:", R.mean())
print("Max:", R.max())


Tensor R:
 tensor([[0.4779, 0.2971, 0.8582, 0.8260],
        [0.2125, 0.0398, 0.1111, 0.6490],
        [0.9769, 0.2273, 0.1844, 0.4680]])

Sum over rows (dim=1): tensor([2.4591, 1.0125, 1.8566])
Sum over columns (dim=0): tensor([1.6673, 0.5642, 1.1537, 1.9430])
Mean: tensor(0.4440)
Max: tensor(0.9769)


dim=0 → operate column-wise
dim=1 → operate row-wise

### Tensor Slicing (Indexing)

In [9]:
print("Original Tensor:\n", R)

print("\nFirst Row:", R[0])
print("First Column:", R[:, 0])
print("Submatrix R[0:2, 1:3]:\n", R[0:2, 1:3])


Original Tensor:
 tensor([[0.4779, 0.2971, 0.8582, 0.8260],
        [0.2125, 0.0398, 0.1111, 0.6490],
        [0.9769, 0.2273, 0.1844, 0.4680]])

First Row: tensor([0.4779, 0.2971, 0.8582, 0.8260])
First Column: tensor([0.4779, 0.2125, 0.9769])
Submatrix R[0:2, 1:3]:
 tensor([[0.2971, 0.8582],
        [0.0398, 0.1111]])


Works very similar to NumPy slicing.

### Automatic Differentiation (PyTorch Autograd)

In [11]:
x = torch.tensor(3.0, requires_grad=True)

# Function f(x) = x² + 2x
f = x**2 + 2*x

# Compute derivative
f.backward()

print("x:", x.item())
print("f(x):", f.item())
print("df/dx:", x.grad.item())


x: 3.0
f(x): 15.0
df/dx: 8.0


PyTorch computes gradients automatically — critical for neural networks.

For f(x) = x² + 2x
df/dx = 2x + 2
At x = 3 → df/dx = 8 ✔

# Summary

Creating tensors

Reshaping and flattening

Broadcasting

Element-wise operations

Matrix operations

Reduction operations (sum/mean/min/max)

Tensor slicing

(Bonus) Auto-differentiation